-- Per-message read tracking
ALTER TABLE dm_messages ADD COLUMN IF NOT EXISTS read_at TIMESTAMP DEFAULT NULL;
ALTER TABLE dm_messages ADD COLUMN IF NOT EXISTS read_by VARCHAR(60) DEFAULT NULL REFERENCES users(id) ON DELETE SET NULL;
