services:
  - type: web
    name: kami-manga-api
    runtime: node
    buildCommand: cd backend && rm -rf node_modules package-lock.json && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: DB_USER
        value: postgres.bojubfastavgvqkogjnj
      - key: DB_PASSWORD
        value: R04022005ramiez
      - key: DB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        value: KamiManga2026_ClaveSecreta_#123
      - key: GOOGLE_CLIENT_ID
        value: 511044284706-a6f4ulqh24pf1o16v69k4iutj1o1o21b.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GIPHY_API_KEY
        value: nxYKvgaFkoDDFcTcwLDpBCjz52NPxeKM
      - key: SUPABASE_URL
        value: https://bojubfastavgvqkogjnj.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvanViZmFzdGF2Z3Zxa29nam5qIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODg3MzQyMSwiZXhwIjoyMDk0NDQ5NDIxfQ.zk3HoIXv6fcA-ZdXIipbeBjWPicImHXqjlW1A5e5niQ"
